### PR TITLE
perf: defer highlighting to reduce first load time

### PR DESCRIPTION
**Pull request by kevinhwang91**
I don’t know what other people think, but I like to start my nvim quickly

### CODE REVIEW

**Comment by kevinhwang91** [comment]
By the way, change the color theme will hi clear, we should add `ColorScheme` to fire highlight again :)

**Review by kyazdani42 — APPROVED** [review]
this is a good idea thanks for the PR

**Comment by akinsho** [comment]
@kyazdani42 this PR breaks the usage for `telescope` think a lot of users are probably being affected by this and it would be safer to revert for now, till maybe they can update their code

**Comment by akinsho** [comment]
image

**Comment by akinsho** [comment]
Although tbh I don't think this change is the best way to optimise the startup time. This plugin doesn't automatically call `setup` which is what creates all the highlights it's instead up to the consumer to call setup or more likely call `get_icon` which implicitly calls `setup`. Perhaps the better way to do this would be for consuming plugins to defer calling setup if possible

**Pull request merged**
