### PR TITLE
add user config

### LINKED ISSUE #9: Support for overrided icons
Hello,

Is it possible to override the icons from this plugin?

I'm the creator from the [adelarsq/vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) plugin, that extends [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons) (and some others) to use emojis instead of overrided fonts. My idea is also to support this plugin.

### PR DESCRIPTION
**Pull request by kyazdani42**
fixes #9

### CODE REVIEW

**Comment by kyazdani42** [comment]
@adelarsq could you test this ?

**Comment by adelarsq** [comment]
Nice! Thanks for the update. I will try to use.

**Comment by adelarsq** [comment]
Thanks @kyazdani42!

I forgot to reply. It's working fine. Just still haven't time to add support on [adelarsq/vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme)

**Comment by kyazdani42** [comment]
no worries :)

**Comment by adelarsq** [comment]
I have added support for this plugin on [vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) 🙂 

@kyazdani42 thanks for your help on this 🎉

**Pull request merged**
