### PR TITLE
add cterm support

### PR DESCRIPTION
**Pull request by sudo0272**
this will set ctermfg as well to support terminal vim that doesn't support guifg

### CODE REVIEW

**Review by kyazdani42 — APPROVED** [review]
thanks :)

**Comment by kyazdani42** [comment]
could you rebase ?

**Comment by sudo0272** [comment]
Since I'm not an advanced git user, is what I did is what I should do?

**Comment by kyazdani42** [comment]
run `git rebase master` from your branch, fix the conflicts, then `git add . && git rebase --continue`, then `git push -f`

**Comment by sudo0272** [comment]
Thanks!

**Comment by kyazdani42** [comment]
still conflicts sorry i merged the mint PR before :/

**Comment by sudo0272** [comment]
sure! the problem is now resolved
sorry for the late response :(

**Review by kyazdani42 — APPROVED** [review]

**Comment by kyazdani42** [comment]
thanks :)

**Pull request merged**
